return {
  --   "folke/flash.nvim",
  --   event = "VeryLazy",
  --   ---@type Flash.Config
  --   opts = {
  --     highlight = {
  --       matches = "Search", -- highlights the matches
  --       current = "IncSearch", -- highlights the current match
  --     },
  --     -- Optionally, you can add more configurations here for other settings
  --   },
  --   keys = {
  --     {
  --       "s",
  --       mode = { "n", "x", "o" },
  --       function()
  --         require("flash").jump()
  --       end,
  --       desc = "Flash",
  --     },
  --     {
  --       "S",
  --       mode = { "n", "x", "o" },
  --       function()
  --         require("flash").treesitter()
  --       end,
  --       desc = "Flash Treesitter",
  --     },
  --     {
  --       "r",
  --       mode = "o",
  --       function()
  --         require("flash").remote()
  --       end,
  --       desc = "Remote Flash",
  --     },
  --     {
  --       "R",
  --       mode = { "o", "x" },
  --       function()
  --         require("flash").treesitter_search()
  --       end,
  --       desc = "Treesitter Search",
  --     },
  --     {
  --       "<c-s>",
  --       mode = { "c" },
  --       function()
  --         require("flash").toggle()
  --       end,
  --       desc = "Toggle Flash Search",
  --     },
  --
  --     -- Add mapping for '/' search
  --     {
  --       "/",
  --       mode = { "n" },
  --       function()
  --         require("flash").jump({ search = true })
  --       end,
  --       desc = "Flash Search",
  --     },
  --   },
}
